import type { ComponentType, SecurityControl, SecurityControlType } from './types';

export const SECURITY_CONTROLS: Record<SecurityControlType, SecurityControl> = {
  'tls': {
    type: 'tls',
    label: 'TLS/HTTPS',
    description: 'Cifra el tráfico en tránsito entre cliente y servidor.',
    riskMitigated: 'Intercepción de datos (MITM), exposición de credenciales.',
    cost: 5,
  },
  'authentication': {
    type: 'authentication',
    label: 'Authentication',
    description: 'Verifica la identidad del usuario o servicio.',
    riskMitigated: 'Acceso no autorizado, suplantación de identidad.',
    cost: 10,
  },
  'authorization': {
    type: 'authorization',
    label: 'Authorization / RBAC',
    description: 'Controla qué puede hacer cada usuario o servicio.',
    riskMitigated: 'Escalada de privilegios, acceso a datos sensibles.',
    cost: 10,
  },
  'waf': {
    type: 'waf',
    label: 'WAF',
    description: 'Filtrado de peticiones maliciosas (SQL injection, XSS, etc.).',
    riskMitigated: 'Inyección SQL, XSS, ataques de capa 7.',
    cost: 30,
  },
  'rate-limiting': {
    type: 'rate-limiting',
    label: 'Rate Limiting',
    description: 'Limita el número de peticiones por unidad de tiempo.',
    riskMitigated: 'Abuso de API, DoS, scraping masivo.',
    cost: 5,
  },
  'firewall': {
    type: 'firewall',
    label: 'Firewall / Security Groups',
    description: 'Restringe qué IPs y puertos pueden acceder a cada componente.',
    riskMitigated: 'Acceso desde redes no autorizadas, exposición innecesaria.',
    cost: 5,
  },
  'private-network': {
    type: 'private-network',
    label: 'Private Network',
    description: 'Aísla componentes internos en una red privada (VPC).',
    riskMitigated: 'Exposición de bases de datos y servicios internos a Internet.',
    cost: 10,
  },
  'encryption-rest': {
    type: 'encryption-rest',
    label: 'Encryption at Rest',
    description: 'Cifra los datos almacenados en disco.',
    riskMitigated: 'Robo de discos, acceso físico a servidores, fugas de backups.',
    cost: 10,
  },
  'secrets-management': {
    type: 'secrets-management',
    label: 'Secrets Management',
    description: 'Gestión centralizada de credenciales y secretos.',
    riskMitigated: 'Credenciales hardcodeadas, rotación manual, fugas en repositorios.',
    cost: 15,
  },
  'audit-logs': {
    type: 'audit-logs',
    label: 'Audit Logs',
    description: 'Registro de todas las operaciones sensibles.',
    riskMitigated: 'Falta de trazabilidad, detección tardía de incidentes.',
    cost: 10,
  },
};

export const COMPONENT_TYPES: ComponentType[] = [
  {
    type: 'frontend',
    label: 'Frontend',
    category: 'frontend',
    icon: 'Monitor',
    color: '#3b82f6',
    description: 'Interfaz de usuario que los usuarios finales interactúan directamente.',
    baseCapacity: 5000,
    baseCost: 10,
    baseLatency: 20,
    baseAvailability: 99.9,
    scalable: false,
    resources: { vcpu: 1, ram: 1, network: 100 },
    securityControls: ['tls', 'rate-limiting', 'waf'],
    educational: {
      what: 'La capa de presentación que el usuario final ve y con la que interactúa. Puede ser una SPA, una app móvil o un sitio SSR.',
      purpose: 'Renderizar la interfaz, capturar la entrada del usuario y comunicarse con el backend mediante HTTP.',
      whenToUse: 'Siempre. Todo sistema necesita una capa de presentación para que los usuarios interactúen.',
      whenNotToUse: 'No aplica como backend ni como capa de datos. No debe contener lógica de negocio sensible.',
      problemsSolved: ['Presentación de información al usuario', 'Captura de entrada', 'Experiencia de usuario'],
      bottlenecks: ['Si sirve assets pesados sin CDN, la latencia aumenta', 'Si no usa compresión, el ancho de banda se satura'],
      securityRisks: ['XSS si no se sanitiza el input', 'Exposición de claves API en el cliente', 'Falta de TLS permite MITM'],
    },
  },
  {
    type: 'backend',
    label: 'Backend',
    category: 'backend',
    icon: 'Server',
    color: '#10b981',
    description: 'Servidor de aplicación que procesa la lógica de negocio.',
    baseCapacity: 500,
    baseCost: 50,
    baseLatency: 50,
    baseAvailability: 99.0,
    scalable: true,
    resources: { vcpu: 2, ram: 4, network: 200 },
    securityControls: ['authentication', 'authorization', 'rate-limiting', 'audit-logs', 'secrets-management'],
    educational: {
      what: 'El servidor de aplicación que ejecuta la lógica de negocio, procesa peticiones y coordina la comunicación entre capas.',
      purpose: 'Recibir peticiones del frontend, aplicar reglas de negocio, leer/escribir datos y devolver respuestas.',
      whenToUse: 'Siempre que haya lógica de negocio, validación de datos o coordinación entre servicios.',
      whenNotToUse: 'No debe almacenar estado si se va a escalar horizontalmente. No debe actuar como base de datos.',
      problemsSolved: ['Procesamiento de lógica de negocio', 'Validación de datos', 'Coordinación entre servicios'],
      bottlenecks: ['CPU: si el workload es CPU-bound, pocas instancias se saturan rápido', 'RAM: si maneja mucho estado en memoria, puede sufrir OOM', 'Si no hay Load Balancer, una sola instancia es un SPOF'],
      securityRisks: ['Falta de autenticación permite acceso no autorizado', 'Credenciales hardcodeadas en código', 'Sin rate limiting es vulnerable a DoS'],
    },
  },
  {
    type: 'api-gateway',
    label: 'API Gateway',
    category: 'infrastructure',
    icon: 'Network',
    color: '#f59e0b',
    description: 'Punto único de entrada que enruta, autentica y limita peticiones.',
    baseCapacity: 3000,
    baseCost: 80,
    baseLatency: 10,
    baseAvailability: 99.9,
    scalable: false,
    resources: { vcpu: 2, ram: 2, network: 500 },
    securityControls: ['tls', 'authentication', 'authorization', 'rate-limiting', 'waf', 'audit-logs'],
    educational: {
      what: 'Un punto único de entrada que enruta peticiones, aplica autenticación, rate limiting y transformaciones.',
      purpose: 'Centralizar la seguridad y el enrutado, desacoplando el frontend de los servicios internos.',
      whenToUse: 'Cuando hay múltiples servicios backend, cuando necesitas rate limiting o autenticación centralizada.',
      whenNotToUse: 'En sistemas muy pequeños con un solo backend puede añadir complejidad y costo innecesarios.',
      problemsSolved: ['Centralización de seguridad', 'Rate limiting', 'Enrutado a múltiples servicios', 'Auditoría de peticiones'],
      bottlenecks: ['Si no hay redundancia, es un SPOF', 'Si no usa caché, reenvía todo el tráfico'],
      securityRisks: ['Sin WAF deja pasar inyecciones', 'Sin rate limiting permite abuso', 'Si cae, todo el sistema queda inaccesible'],
    },
  },
  {
    type: 'load-balancer',
    label: 'Load Balancer',
    category: 'infrastructure',
    icon: 'Shuffle',
    color: '#f97316',
    description: 'Distribuye el tráfico entre múltiples instancias para alta disponibilidad.',
    baseCapacity: 10000,
    baseCost: 100,
    baseLatency: 5,
    baseAvailability: 99.99,
    scalable: false,
    resources: { vcpu: 2, ram: 2, network: 1000 },
    securityControls: ['tls', 'firewall', 'private-network'],
    educational: {
      what: 'Distribuye el tráfico entrante entre múltiples instancias de backend para evitar sobrecarga y proporcionar failover.',
      purpose: 'Mejorar disponibilidad y escalabilidad horizontal distribuyendo carga entre instancias.',
      whenToUse: 'Cuando hay múltiples instancias de backend o cuando se necesita alta disponibilidad.',
      whenNotToUse: 'Con un solo backend y pocos usuarios es costo innecesario.',
      problemsSolved: ['Distribución de carga', 'Failover automático', 'Escalado horizontal'],
      bottlenecks: ['Si no hay health checks, puede enrutar a instancias caídas', 'Si es un SPOF sin redundancia, todo el sistema depende de él'],
      securityRisks: ['Sin TLS termina el tráfico en claro', 'Si no filtra tráfico malicioso, pasa todo al backend'],
    },
  },
  {
    type: 'redis',
    label: 'Redis',
    category: 'cache',
    icon: 'Database',
    color: '#ef4444',
    description: 'Caché en memoria para reducir latencia y carga en la base de datos.',
    baseCapacity: 8000,
    baseCost: 60,
    baseLatency: 2,
    baseAvailability: 99.5,
    scalable: false,
    resources: { vcpu: 1, ram: 8, network: 300 },
    securityControls: ['firewall', 'private-network', 'encryption-rest'],
    educational: {
      what: 'Almacén de datos en memoria (key-value) usado como caché, cola de mensajes o sesión.',
      purpose: 'Reducir la latencia de lecturas repetidas y descargar a la base de datos de consultas frecuentes.',
      whenToUse: 'Cuando hay muchas lecturas repetidas, cuando la latencia de la base de datos es un cuello de botella.',
      whenNotToUse: 'Para datos que requieren ACID completo. Como única fuente de datos (es volátil por naturaleza).',
      problemsSolved: ['Reduce latencia de lecturas', 'Descarga a la base de datos', 'Sesiones distribuidas'],
      bottlenecks: ['RAM: si se llena, empieza a evictar claves y el cache hit rate cae', 'Si cae, toda la carga va a PostgreSQL de golpe'],
      securityRisks: ['Sin firewall puede ser accesible públicamente', 'Sin cifrado en reposo expone datos en memoria', 'Sin autenticación permite acceso libre'],
    },
  },
  {
    type: 'postgresql',
    label: 'PostgreSQL',
    category: 'database',
    icon: 'HardDrive',
    color: '#6366f1',
    description: 'Base de datos relacional ACID para almacenamiento persistente.',
    baseCapacity: 1000,
    baseCost: 120,
    baseLatency: 15,
    baseAvailability: 99.0,
    scalable: false,
    resources: { vcpu: 4, ram: 8, network: 200 },
    securityControls: ['firewall', 'private-network', 'encryption-rest', 'audit-logs', 'secrets-management'],
    educational: {
      what: 'Sistema de base de datos relacional ACID que garantiza consistencia y durabilidad de los datos.',
      purpose: 'Almacenar datos persistentes con garantías de integridad, soportar consultas SQL complejas.',
      whenToUse: 'Siempre que se necesite persistencia con consistencia, transacciones ACID o consultas relacionales.',
      whenNotToUse: 'Como caché (usa Redis). Para datos temporales. Para escalado horizontal simple (no sharding nativo).',
      problemsSolved: ['Persistencia durable', 'Integridad referencial', 'Consultas complejas', 'Transacciones ACID'],
      bottlenecks: ['Conexiones: sin pooling, cada cliente abre una conexión costosa', 'IOPS: si el disco es lento, las escrituras se acumulan', 'Sin índices, las consultas hacen full table scan', 'Sin read replica, toda la carga de lectura va al primario'],
      securityRisks: ['Accesible públicamente sin firewall', 'Sin cifrado en reposo expone datos en disco', 'Sin auditoría no hay trazabilidad de accesos'],
    },
  },
  {
    type: 'kafka',
    label: 'Kafka',
    category: 'messaging',
    icon: 'Radio',
    color: '#8b5cf6',
    description: 'Bus de mensajes para comunicación asíncrona entre servicios.',
    baseCapacity: 5000,
    baseCost: 150,
    baseLatency: 5,
    baseAvailability: 99.9,
    scalable: false,
    resources: { vcpu: 2, ram: 4, network: 500 },
    securityControls: ['tls', 'authentication', 'authorization', 'private-network', 'audit-logs'],
    educational: {
      what: 'Sistema de mensajería distribuida que permite comunicación asíncrona, durable y escalable entre servicios.',
      purpose: 'Desacoplar productores y consumidores, absorber picos de tráfico y garantizar durabilidad de mensajes.',
      whenToUse: 'Cuando necesitas procesamiento asíncrono, desacoplar servicios o garantizar que no se pierdan mensajes.',
      whenNotToUse: 'Para comunicación síncrona. En sistemas pequeños donde la complejidad no se justifica.',
      problemsSolved: ['Desacoplamiento entre servicios', 'Durabilidad de mensajes', 'Absorción de picos', 'Procesamiento asíncrono'],
      bottlenecks: ['Si los consumidores son lentos, los mensajes se acumulan', 'Sin particiones suficientes, el paralelismo es limitado'],
      securityRisks: ['Sin TLS los mensajes viajan en claro', 'Sin autenticación cualquier servicio puede producir/consumir', 'Sin auditoría no hay trazabilidad de eventos'],
    },
  },
  {
    type: 'queue',
    label: 'Queue',
    category: 'messaging',
    icon: 'ListOrdered',
    color: '#ec4899',
    description: 'Cola de tareas para procesamiento asíncrono y desacoplado.',
    baseCapacity: 3000,
    baseCost: 90,
    baseLatency: 8,
    baseAvailability: 99.5,
    scalable: false,
    resources: { vcpu: 1, ram: 2, network: 200 },
    securityControls: ['tls', 'authentication', 'private-network'],
    educational: {
      what: 'Cola de tareas que permite encolar trabajo pesado para procesarlo de forma asíncrona y desacoplada.',
      purpose: 'Desacoplar la producción de tareas de su procesamiento, permitir reintentos y procesamiento en segundo plano.',
      whenToUse: 'Cuando hay tareas pesadas (envío de email, procesamiento de pagos) que no deben bloquear la respuesta al usuario.',
      whenNotToUse: 'Para comunicación síncrona. Si necesitas ordering estricto entre múltiples consumidores.',
      problemsSolved: ['Procesamiento asíncrono', 'Reintentos automáticos', 'Desacoplamiento', 'Absorción de picos'],
      bottlenecks: ['Si los workers son lentos, la cola crece indefinidamente', 'Sin dead letter queue, los mensajes fallidos se pierden'],
      securityRisks: ['Sin TLS expone el contenido de las tareas', 'Sin autenticación cualquier servicio puede encolar tareas'],
    },
  },
];

export const COMPONENT_MAP: Record<string, ComponentType> = COMPONENT_TYPES.reduce(
  (acc, c) => ({ ...acc, [c.type]: c }),
  {} as Record<string, ComponentType>
);
